# Select the command that will
# be executed from the player.
# Credits: @hexyyy fixed by @darknesslocalhost
# Website: laststyle.tk
# 
#
command: "help" # the command to execute the join event, for example say 

